export const TYPES = {
  SET_USER: 'SET_USER',
  CLEAR_USER: 'CLEAR_USER',
  AUTH_ERROR: 'AUTH_ERROR',
  CHANNEL_ADDED: 'CHANNEL_ADDED',
  CHANNEL_ADD_FAILED: 'CHANNEL_ADDED_FAILED',
  CHANNELS_BY_ADMIN: 'CHANNELS_BY_ADMIN',

  CURENT_USER_INFO: 'CURENT_USER_INFO',

  USER_ADDED_TO_CHANNEL: 'USER_ADDED_TO_CHANNEL',
  ERROR_ADDING_USER_TO_CHANNEL: 'ERROR_ADDING_USER_TO_CHANNEL',

  USER_REMOVED_FROM_CHANNEL: 'USER_REMOVED_FROM_CHANNEL',
  ERROR_REMOVING_USER_FROM_CHANNEL: 'ERROR_REMOVING_USER_FROM_CHANNEL',

  ADD_CHANNEL_TO_FAV: 'ADD_CHANNEL_TO_FAV',
  ADD_CHANNEL_TO_FAV_ERROR: 'ADD_CHANNEL_TO_FAV',
  REMOVE_CHANNEL_FROM_FAV: 'REMOVE_CHANNEL_FROM_FAV',
  REMOVE_CHANNEL_FROM_FAV_ERROR: 'REMOVE_CHANNEL_FROM_FAV',

  GET_ALL_CHANNELS: 'GET_ALL_CHANNELS',
  MESSAGE_SENT: 'MESSAGE_SENT',
  MESSAGE_SENT_FAILED: 'MESSAGE_SENT_FAILED',
  MESSAGE_LIST: 'MESSAGE_LIST',

  CURRENT_CHANNEL: 'CURRENT_CHANNEL',
  CURRENT_CHANNEL_INFO: 'CURRENT_CHANNEL_INFO',
  GET_ALL_USERS: 'GET_ALL_USERS'
}
